### ISSUE TITLE
[qt5] rqt_graph on xenial: "cannot import name QGraphicsPathItem"

### ISSUE THREAD

**Issue by neopostmodern** [ros-visualization/rqt_common_plugins#367]
I'm trying to set up a new machine running Ubuntu Xenial and ROS kinetic. Because `rqt_common_plugins` isn't available in the repos yet, I cloned the `qt5` branch, installed a lot of dependencies, `catkin_make install`, `. install/setup.sh` and that works now.

But when running `rosrun rqt_graph rqt_graph` I get this nice error message:
```
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
RosPluginProvider.load(rqt_graph/RosGraph) exception raised in __builtin__.__import__(rqt_graph.ros_graph, [RosGraph]):
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 77, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/home/neopostmodern/University/6/Robotics/rqt_common_plugins/install/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 45, in <module>
    from qt_dotgraph.dot_to_qt import DotToQtGenerator
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_dotgraph/dot_to_qt.py", line 41, in <module>
    from .edge_item import EdgeItem
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_dotgraph/edge_item.py", line 32, in <module>
    from python_qt_binding.QtGui import QBrush, QGraphicsPathItem, QGraphicsPolygonItem, QGraphicsSimpleTextItem, QPainterPath, QPen, QPolygonF
ImportError: cannot import name QGraphicsPathItem

PluginManager._load_plugin() could not load plugin "rqt_graph/RosGraph":
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 99, in load
    self._load()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 83, in load
    raise e
ImportError: cannot import name QGraphicsPathItem
```

(This is specific to `qt_graph`. I ran `rqt_topic` and some other packages without issues.)

**Comment by dirk-thomas** [comment]
Well, Kinetic hasn't been announced yet and this repo hasn't been released for Kinetic either. So I don't think this needs to be documented in the README. In generat when you build something from source you need to check if you have all dependencies which might imply newer dependencies. In the case of `qt_gui_core` the necessary version has already been released but is currently only available in the testing repo: http://repositories.ros.org/status_page/ros_kinetic_default.html?q=qt_gui_core

I will close this since it seems to be resolved with current dependencies. And when this repo is released the dependencies will already be available from the public repo.

Thanks for trying it.
