### ISSUE TITLE
rqt_graph dot_to_qt raises an exception

### ISSUE THREAD

**Issue by anlif** [ros-visualization/rqt_common_plugins#393]
I get the following error with ROS indigo version 1.11.20, pydot version 1.2.2 and rqt_graph version 0.3.13 (according to the package.xml) when launching rqt_graph (just roscore running):

> PluginHandlerDirect._restore_settings() plugin "rqt_graph/RosGraph#0" raised an exception:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/qt_gui/plugin_handler_direct.py", line 116, in _restore_settings
    self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
  File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_graph/ros_graph.py", line 202, in restore_settings
    self._refresh_rosgraph()
  File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_graph/ros_graph.py", line 226, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_graph/ros_graph.py", line 259, in _update_graph_view
    self._redraw_graph_view()
  File "/opt/ros/indigo/lib/python2.7/site-packages/rqt_graph/ros_graph.py", line 292, in _redraw_graph_view
    same_label_siblings=True)
  File "/opt/ros/indigo/lib/python2.7/site-packages/qt_dotgraph/dot_to_qt.py", line 254, in dotcode_to_qt_items
    graph.nodes_iter = graph.get_node_list
AttributeError: 'list' object has no attribute 'get_node_list'
> 

However, when downgrading to pydot version 1.0.29 rqt_graph works fine. I'm guessing this might just be a dependency issue, but I'm posting it here just in case something needs to be updated according to pydot.

See also http://answers.ros.org/question/239274/rqt_graph-rqt_tf_tree-issue-ros-indigo/

**Comment by dirk-thomas** [comment]
It looks like newer versions of `pydot` changed the semantic of the API: https://github.com/erocarrera/pydot/blob/69dce474f6fbcaa6055586611453e43f3f20230d/ChangeLog#L25-L30

I created #70 to handle both cases. You can apply the patch to you locally installed file (`/opt/ros/<DISTRO</lib/python2.7/dist-packages/qt_dotgraph/dot_to_qt.py`) and go back to latest version of `pydot`.
