### ISSUE TITLE
rqt_reconfigure: crash with "hide" or "collapse" group type

### ISSUE THREAD

**Issue by plugz** [ros-visualization/rqt_common_plugins#418]
Trying to display a group with type "hide" or "collapse" will make rqt_reconfigure crash.

This crash happens on kinetic, but not on indigo.

Here's a backtrace:
```Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/node_selector_widget.py", line 275, in _selection_changed_slot
    self._selection_selected(index_current, rosnode_name_selected)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/node_selector_widget.py", line 225, in _selection_selected
    item_widget = item_child.get_dynreconf_widget()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/treenode_qstditem.py", line 154, in get_dynreconf_widget
    self._param_name_raw)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/dynreconf_client_widget.py", line 57, in __init__
    group_desc, node_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/param_groups.py", line 152, in __init__
    self._create_node_widgets(config)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/param_groups.py", line 198, in _create_node_widgets
    widget = eval(_GROUP_TYPES[group['type']])(self.updater, group, self._toplevel_treenode_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_reconfigure/param_groups.py", line 279, in __init__
    self.box.setShown(self.state)
AttributeError: 'QGroupBox' object has no attribute 'setShown'

**Comment by dirk-thomas** [comment]
Looks like this was Qt 3 legacy API which only existed in Qt 4 for compatibility and was removed in Qt 5: https://doc-snapshots.qt.io/4.8/qwidget-qt3.html#setShown

Fixed in cd3b2afb88c0fd50229b3868bf6c48951e53066c.
