### ISSUE TITLE
rqt_launch crashes on ros kinetic

### ISSUE THREAD

**Issue by jrahlf** [ros-visualization/rqt_common_plugins#422]
Hi,

I get the following error when launching rqt_launch in conjunction with ros kinetic:

```
~$ rqt --standalone rqt_launch
[INFO] [1485795137.664887]: LaunchWidget master_uri=http://172.24.1.1:11311
/usr/lib/python2.7/threading.py:1151: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
  return _active[_get_ident()]
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_launch/launch_widget.py", line 138, in _load_launchfile_slot
    self._create_widgets_for_launchfile(_config)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_launch/launch_widget.py", line 184, in _create_widgets_for_launchfile
    proxy = NodeProxy(self._run_id, self._config.master.uri, node)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_launch/node_proxy.py", line 69, in __init__
    self._process = self.recreate_process()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_launch/node_proxy.py", line 97, in recreate_process
    self._run_id, self.config, self.master_uri)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/nodeprocess.py", line 116, in create_node_process
    _logger.info("create_node_process: package[%s] type[%s] machine[%s] master_uri[%s]", node.package, node.type, node.machine, master_uri)
  File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1285, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1259, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 285, in __init__
    self.threadName = threading.current_thread().name
  File "/usr/lib/python2.7/threading.py", line 1151, in currentThread
    return _active[_get_ident()]
TypeError: cannot create weak reference to 'NodeController' object
```

[rqt-crash.txt](https://github.com/ros-visualization/rqt_common_plugins/files/739632/rqt-crash.txt)

Running the plugin within rqt produces the same result.
Any ideas how i can get rqt_launch to work?

Kind regards

**Comment by dirk-thomas** [comment]
Thanks for the report. #423 should fix the problem.
