### ISSUE TITLE
rqt_graph crashes on kinetic   if (enable_statistics == true)

### ISSUE THREAD

**Issue by jrahlf** [ros-visualization/rqt_common_plugins#428]
Hi,

for me rqt_graph crashes on kinetic, if the rosparam enable_statistics has been set to true.

See the attached log for details.

`$ rqt_graph 
PluginHandlerDirect._restore_settings() plugin "rqt_graph/RosGraph#0" raised an exception:
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 116, in _restore_settings
    self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 203, in restore_settings
    self._refresh_rosgraph()
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 227, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 254, in _generate_dotcode
    quiet=quiet)
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 578, in generate_dotcode
    quiet=quiet)
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 521, in generate_dotgraph
    self._add_edge(e, dotcode_factory, dotgraph=dotgraph, is_topic=(graph_mode == NODE_NODE_GRAPH))
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 213, in _add_edge
    [stat_label, penwidth, color] = self._calc_statistic_info(sub, topic)
  File "/home/dyecam/catkin_ws/install_isolated/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 175, in _calc_statistic_info
    pub = next(self.edges[sub][topic].keys())
TypeError: list object is not an iterator
`

[rqt-crash.txt](https://github.com/ros-visualization/rqt_common_plugins/files/758517/rqt-crash.txt)

Kind regards

**Comment by dirk-thomas** [comment]
I can't reproduce the problem. Can you please provide more information (which exact version of `rqt_graph` as well as `qt_dotgraph` are you using?) and a reproducible example (http://sscce.org/).
