### ISSUE TITLE
rqt_launch) Errors happening in roslaunch are not taken care of

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_common_plugins#72]
Similar to Issue #53 but the phenomenon is different. Thus opened as a separate issue.

On `rqt_launch` when I open `demo.launch` from `pr2_moveit_config` pkg, no nodes are shown, nothing happens on GUI and I only see this on commandline:

```
Traceback (most recent call last):
  File "/home/user/ros/rqt_common_plugins/rqt_launch/src/rqt_launch/launch_widget.py", line 120, in _load_launchfile_slot
    self._port_roscore)
  File "/home/user/ros/rqt_common_plugins/rqt_launch/src/rqt_launch/launch_widget.py", line 156, in _create_launchconfig
    port_roscore)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/config.py", line 428, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 694, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 666, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 630, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 571, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 610, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 236, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/loader.py", line 453, in param_value
    with open(textfile, 'r') as f:
```

When opening `moveit_group.launch`, error gets different:

```
Traceback (most recent call last):
  File "/home/user/ros/rqt_common_plugins/rqt_launch/src/rqt_launch/launch_widget.py", line 137, in _load_launchfile_slot
    self._create_widgets_for_launchfile(_config)
  File "/home/user/ros/rqt_common_plugins/rqt_launch/src/rqt_launch/launch_widget.py", line 183, in _create_widgets_for_launchfile
    proxy = NodeProxy(self._run_id, self._config.master.uri, node)
  File "/home/user/ros/rqt_common_plugins/rqt_launch/src/rqt_launch/node_proxy.py", line 69, in __init__
    self._process = self.recreate_process()
  File "/home/user/ros/rqt_common_plugins/rqt_launch/src/rqt_launch/node_proxy.py", line 95, in recreate_process
    self._run_id, self.config, self.master_uri)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/nodeprocess.py", line 131, in create_node_process
    args = create_local_process_args(node, machine)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/node_args.py", line 239, in create_local_process_args
    raise NodeParamsException("can't locate node [%s] in package [%s]"%(node.type, node.package))
roslaunch.node_args.NodeParamsException: can't locate node [move_group] in package [moveit_ros_move_group]
```

Both of these just indicate that `roslaunch` cannot open certain `.launch` files. So `rqt_launch` has to be able to handle them, notify them to the users.

`rqt_launch` 6238299e7b036b88f42979829ad3c0aea895aae6

**Comment by dirk-thomas** [comment]
This issue was moved to ros-visualization/rqt_launch#8
